### ISSUE TITLE
what is the license of heimdalljs-lib?

### ISSUE THREAD

**Issue by luisapace** [heimdalljs/heimdalljs-lib#124]
Hi, my team would like to use this package, and to approve it I've to approve its license, could you please the license of heimdalljs-lib?

Thanks.

**Comment by hjdivad** [comment]
@luisapace the `package.json` of each published package in this mono-repo correctly lists the license as MIT.

That said we haven't been packing them with a copy of the license; #125 to fix that.

**Comment by luisapace** [comment]
many thanks for your fast follow-on!
