### ISSUE TITLE
slice time between children

### ISSUE THREAD

**Issue by hjdivad** [heimdalljs/heimdalljs-lib#14]
if parent a has children b, c we currently report three times
- `a` selftime
- `b` selftime
- `c` selftime

but it is often interesting to know time (and other stats) of `a` separated between (0-b), (b-c), (c-end).

Seems like this could be done by utilizing a fix for #13

**Comment by hjdivad** [comment]
It's worth noting that merely doing #15 handles this for times.

To get it for counters as well, we may want to do something like

- leaf nodes only have counters
- when a leaf node becomes an intermediate node, do a conversion that shifts the counters into a first child.

eg

```
```

**Comment by runspired** [comment]
This landed as 0.3
