### ISSUE TITLE
top level `time.self` subtraction is confusing

### ISSUE THREAD

**Issue by runspired** [heimdalljs/heimdalljs-lib#23]
Reading through the code, I'm not sure this is a real issue/bug, but I'm seeing something
roughly like the below at the moment.

Given a tree that looks roughly like below.

```
A 
|_ B
   |_ C
```

Assuming the total time spent in A was `10ms`, B was `10ms` and C was `4ms`,
currently `stats.time.self` will report

```
A: `5ms` (roughly 50% of total time)
B: `10ms`
C: `4ms`
```

Where A has subtracted the time spent in the furthest leaves only, and B has subtracted nothing at all.  Real world example of this is below:

<img width="544" alt="screen shot 2016-08-23 at 8 47 46 pm" src="https://cloud.githubusercontent.com/assets/650309/17917991/ef0dd908-6975-11e6-8aa4-88eb4e7049b1.png">

Reading through the implementation I would have expected this:

```
A: `0ms` (10 - 10)
B: `6ms` ( 10 - 4)
C: `4ms`
```

**Comment by hjdivad** [comment]
@runspired your expectations are correct as far as what's intended.  Sounds like a bug; let's dig into this this morning

**Comment by hjdivad** [comment]
ran through this with @runspired; the bug was with the analysis tool not the data collection in heimdall
