### ISSUE TITLE
heimdalljs@0.2.2 TypeError: heimdall.statsFor is not a function

### ISSUE THREAD

**Issue by chriscareycode** [heimdalljs/heimdalljs-lib#39]
Getting this error starting today. 0.2.1 not having the problem
heimdalljs@0.2.2 
heimdalljs-fs-monitor@0.0.3 
heimdalljs-logger@0.1.7

**Comment by chriscareycode** [comment]
https://github.com/ember-cli/ember-cli/issues/6434

**Comment by derekdowling** [comment]
This should still be open. The underlying error is coming from version 0.2.2 of this library.

**Comment by derekdowling** [comment]
The only reference to `statsFor` I could find is here: https://github.com/heimdalljs/heimdall-fs-monitor/blob/c0f21c2f0eef2581f0ed064b59adc850fa3dca1d/index.js#L59.

**Comment by hjdivad** [comment]
@derekdowling yeah v0.2.2 is broken; i have released v0.2.3 which resolved this issue
