### ISSUE TITLE
add appveyor

### ISSUE THREAD

**Issue by stefanpenner** [heimdalljs/heimdalljs-lib#45]
- [x] config -> https://github.com/heimdalljs/heimdalljs-lib/pull/66/commits/65e674fc9482c70466232f134de1c384ca00c62d

- [x] enable appveyor (stef is having issues for some reason)

**Comment by stefanpenner** [comment]
Added a potential appveyor.yml -> https://github.com/heimdalljs/heimdalljs-lib/pull/66/commits/65e674fc9482c70466232f134de1c384ca00c62d

Although I am an admin here, i am unable to add this repo to appveyor itself....

**Comment by stefanpenner** [comment]
@hjdivad  / @runspired mind giving enabling appveyor a try, for some reason heimdalljs org isn't showing up for me from the UI.

**Comment by hjdivad** [comment]
appveyor enabled: https://ci.appveyor.com/project/hjdivad/heimdalljs-lib

seems like things are currently broken in windows
