### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by twokul** [heimdalljs/heimdalljs-lib#65]
I was reading through the code and found myself thinking that types would help to grok it does much faster. Would there be any objections to convert to Typescript? If so, I volunteer to do the work.

/cc @runspired @hjdivad @stefanpenner @rwjblue

**Comment by runspired** [comment]
I think we would all be on board with this.

**Comment by stefanpenner** [comment]
its fine to migrate, but no need keeping an issue open.

**Comment by hjdivad** [comment]
I'm 👍 on typescript-style incremental type annotation.
