### ISSUE TITLE
build broken in windows

### ISSUE THREAD

**Issue by hjdivad** [heimdalljs/heimdalljs-lib#67]
https://ci.appveyor.com/project/hjdivad/heimdalljs-lib

**Comment by rwjblue** [comment]
I had a theory there might be broken windows... :trollface:

**Comment by hjdivad** [comment]
@rwjblue how does github not have :facepalm: as a reaction?

Obviously we don't live in the best of all possible worlds.

**Comment by rwjblue** [comment]
HAHA, I don't know, but I couldn't resist 😝

**Comment by runspired** [comment]
fixed: https://github.com/heimdalljs/heimdalljs-lib/pull/73
